runtime: nodejs12

service: api

includes:
  - env_vars.yaml

handlers:
  - url: /
    static_files: application/public/index.html
    upload: application/public/index.html

  - url: /
    static_dir: application/public